/*
 * File: app/store/CinemaStore.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.CinemaStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.CinemasModel'
    ],

    config: {
        autoLoad: false,
        autoSync: false,
        data: [
            {
                name: 'Olympus Sheraton',
                address: 'Sheraton Mall, Christ Church',
                imageurl: 'http://www.iplanit.ie/wp-content/uploads/2012/10/olympus-horizontal.jpg',
                logourl: 'http://www.iplanit.ie/wp-content/uploads/2012/10/olympus-logo.jpeg',
                email: 'office@olympus.bb',
                phone: '(246) 228-5255'
            },
            {
                name: 'Globe Drive-In',
                address: 'Adam\'s Castle, Christ Church',
                imageurl: 'resources/images/noimage-large.gif',
                logourl: 'resources/images/noimage.gif',
                email: 'office@globedivein.bb',
                phone: '(246) 228-5255'
            },
            {
                name: 'Limegrove',
                address: 'Holetown, St. James',
                imageurl: 'http://www.iplanit.ie/wp-content/uploads/2012/10/limegrove-horizontal.jpg',
                logourl: 'http://www.iplanit.ie/wp-content/uploads/2012/10/limegrove-icon-logo.gif',
                email: 'office@ilmegrove.bb',
                phone: '(246) 228-5255'
            }
        ],
        model: 'MyApp.model.CinemasModel',
        storeId: 'CinemaStore',
        proxy: {
            type: 'ajax',
            reader: {
                type: 'json',
                rootProperty: 'data'
            }
        }
    }
});