/*
 * File: app/store/CinemaStore.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AppBarbados.store.CinemaStore', {
    extend: 'Ext.data.Store',
    alias: 'store.CinemaStore',

    requires: [
        'AppBarbados.model.cinema'
    ],

    config: {
        autoLoad: false,
        autoSync: false,
        data: [
            {
                id: 1,
                name: 'Olympus Sheraton',
                address: 'Sheraton Mall, Christ Church',
                imageUrl: 'http://www.iplanit.ie/wp-content/uploads/2012/10/olympus-horizontal.jpg',
                logoUrl: 'http://www.iplanit.ie/wp-content/uploads/2012/10/olympus-logo.jpeg',
                email: 'office@olympus.bb',
                phone: '(246) 228-5255',
                movies: [
                    {
                        id: 1,
                        title: 'Total Recall',
                        description: 'When a man goes for virtual vacation memories of the planet Mars, an unexpected and harrowing series of events forces him to go to the planet for real, or does he?',
                        imageUrl: 'http://t1.gstatic.com/images?q=tbn:ANd9GcS-89ASsLirzbuNm9p6_UWFeVOQC4GqpB3tu6zf1aWT-c1nI8wr9Gu1--zw',
                        logoUrl: 'http://t1.gstatic.com/images?q=tbn:ANd9GcS-89ASsLirzbuNm9p6_UWFeVOQC4GqpB3tu6zf1aWT-c1nI8wr9Gu1--zw',
                        trailerUrl: 'http://www.youtube.com/watch?v=MLAvdQF7Ypo',
                        showTimesToday: '<div class=little-button>12:30</div><div class=little-button>17:00</div><div class=little-button>20:00</div>',
                        showTimesWeek: 'Showtimes this week:<br><div style=\'text-align: left; font-size: 13px; clear:both\'>Today: (09/11/2012)<br><div class=little-button>12:30</div><div class=little-button>17:00</div><div class=little-button>20:00</div></div><div style="text-align: left; font-size: 13px; clear:both">Saturday (10/11/2012)<br><div class="little-button">12:30</div><div class="little-button">17:00</div><div class="little-button">20:00</div><div style="text-align: left; font-size: 13px; clear:both">Sunday (11/11/2012)<br><div class="little-button">12:30</div><div class="little-button">17:00</div><div class="little-button">20:00</div></div></div>'
                    },
                    {
                        id: 2,
                        title: 'Anna Karenina',
                        description: 'Set in late-19th-century Russia high-society, the aristocrat Anna Karenina enters into a life-changing affair with the affluent Count Vronsky.',
                        imageUrl: 'http://t1.gstatic.com/images?q=tbn:ANd9GcT75AYSk_CjiBVUsSgkvaIuIBLuQxCM19l1vFcEsb3pYtlRw_ZeQlRIIIeshA',
                        logoUrl: 'http://t1.gstatic.com/images?q=tbn:ANd9GcT75AYSk_CjiBVUsSgkvaIuIBLuQxCM19l1vFcEsb3pYtlRw_ZeQlRIIIeshA',
                        trailerUrl: 'http://www.youtube.com/watch?v=rPGLRO3fZnQ',
                        showTimesToday: '<div class=little-button>13:20</div><div class=little-button>16:40</div><div class=little-button>18:00</div><div class=little-button>19:30</div><div class=little-button>21:20</div><div class=little-button>22:50</div>',
                        showTimesWeek: 'Showtimes this week:<br><div style=\'text-align: left; font-size: 13px; clear:both\'>Today: (09/11/2012)<br><div class=little-button>13:20</div><div class=little-button>16:40</div><div class=little-button>18:00</div><div class=little-button>19:30</div><div class=little-button>21:20</div><div class=little-button>22:50</div></div><div style="text-align: left; font-size: 13px; clear:both">Saturday (10/11/2012)<br><div class="little-button">12:30</div><div class="little-button">17:00</div><div class="little-button">20:00</div><div style="text-align: left; font-size: 13px; clear:both">Sunday (11/11/2012)<br><div class="little-button">12:30</div><div class="little-button">20:00</div></div></div>'
                    }
                ]
            },
            {
                id: 2,
                name: 'Globe Drive-In',
                address: 'Adam\'s Castle, Christ Church',
                imageUrl: 'resources/images/noimage-large.gif',
                logoUrl: 'resources/images/noimage.gif',
                email: 'office@globedivein.bb',
                phone: '(246) 228-5255',
                movies: [
                    {
                        id: 1,
                        title: 'Anna Karenina',
                        description: 'Set in late-19th-century Russia high-society, the aristocrat Anna Karenina enters into a life-changing affair with the affluent Count Vronsky.',
                        imageUrl: 'http://t1.gstatic.com/images?q=tbn:ANd9GcT75AYSk_CjiBVUsSgkvaIuIBLuQxCM19l1vFcEsb3pYtlRw_ZeQlRIIIeshA',
                        logoUrl: 'http://t1.gstatic.com/images?q=tbn:ANd9GcT75AYSk_CjiBVUsSgkvaIuIBLuQxCM19l1vFcEsb3pYtlRw_ZeQlRIIIeshA',
                        trailerUrl: 'http://www.youtube.com/watch?v=rPGLRO3fZnQ',
                        showTimesToday: '<div class=little-button>13:20</div><div class=little-button>16:40</div><div class=little-button>18:00</div><div class=little-button>19:30</div><div class=little-button>21:20</div><div class=little-button>22:50</div>',
                        showTimesWeek: 'Showtimes this week:<br><div style=\'text-align: left; font-size: 13px; clear:both\'>Today: (09/11/2012)<br><div class=little-button>13:20</div><div class=little-button>16:40</div><div class=little-button>18:00</div><div class=little-button>19:30</div><div class=little-button>21:20</div><div class=little-button>22:50</div></div><div style="text-align: left; font-size: 13px; clear:both">Saturday (10/11/2012)<br><div class="little-button">12:30</div><div class="little-button">17:00</div><div class="little-button">20:00</div><div style="text-align: left; font-size: 13px; clear:both">Sunday (11/11/2012)<br><div class="little-button">12:30</div><div class="little-button">20:00</div></div></div>'
                    },
                    {
                        id: 2,
                        title: 'Total Recall',
                        description: 'When a man goes for virtual vacation memories of the planet Mars, an unexpected and harrowing series of events forces him to go to the planet for real, or does he?',
                        imageUrl: 'http://t1.gstatic.com/images?q=tbn:ANd9GcS-89ASsLirzbuNm9p6_UWFeVOQC4GqpB3tu6zf1aWT-c1nI8wr9Gu1--zw',
                        logoUrl: 'hhttp://t1.gstatic.com/images?q=tbn:ANd9GcS-89ASsLirzbuNm9p6_UWFeVOQC4GqpB3tu6zf1aWT-c1nI8wr9Gu1--zw',
                        trailerUrl: 'http://www.youtube.com/watch?v=MLAvdQF7Ypo',
                        showTimesToday: '<div class=little-button>12:30</div><div class=little-button>17:00</div><div class=little-button>20:00</div>',
                        showTimesWeek: 'Showtimes this week:<br><div style=\'text-align: left; font-size: 13px; clear:both\'>Today: (09/11/2012)<br><div class=little-button>12:30</div><div class=little-button>17:00</div><div class=little-button>20:00</div></div><div style="text-align: left; font-size: 13px; clear:both">Saturday (10/11/2012)<br><div class="little-button">12:30</div><div class="little-button">17:00</div><div class="little-button">20:00</div><div style="text-align: left; font-size: 13px; clear:both">Sunday (11/11/2012)<br><div class="little-button">12:30</div><div class="little-button">20:00</div></div></div>'
                    }
                ]
            },
            {
                id: 3,
                name: 'Limegrove',
                address: 'Holetown, St. James',
                imageUrl: 'http://www.iplanit.ie/wp-content/uploads/2012/10/limegrove-horizontal.jpg',
                logoUrl: 'http://www.iplanit.ie/wp-content/uploads/2012/10/limegrove-icon-logo.gif',
                email: 'office@ilmegrove.bb',
                phone: '(246) 228-5255',
                movies: [
                    {
                        id: 1,
                        title: 'Total Recall',
                        description: 'When a man goes for virtual vacation memories of the planet Mars, an unexpected and harrowing series of events forces him to go to the planet for real, or does he?',
                        imageUrl: 'http://t1.gstatic.com/images?q=tbn:ANd9GcS-89ASsLirzbuNm9p6_UWFeVOQC4GqpB3tu6zf1aWT-c1nI8wr9Gu1--zw',
                        logoUrl: 'http://t1.gstatic.com/images?q=tbn:ANd9GcS-89ASsLirzbuNm9p6_UWFeVOQC4GqpB3tu6zf1aWT-c1nI8wr9Gu1--zw',
                        trailerUrl: 'http://www.youtube.com/watch?v=MLAvdQF7Ypo',
                        showTimesToday: '<div class=little-button>13:20</div><div class=little-button>16:40</div><div class=little-button>18:00</div><div class=little-button>19:30</div><div class=little-button>21:20</div><div class=little-button>22:50</div>',
                        showTimesWeek: 'Showtimes this week:<br><div style=\'text-align: left; font-size: 13px; clear:both\'>Today: (09/11/2012)<br><div class=little-button>13:20</div><div class=little-button>16:40</div><div class=little-button>18:00</div><div class=little-button>19:30</div><div class=little-button>21:20</div><div class=little-button>22:50</div></div><div style="text-align: left; font-size: 13px; clear:both">Saturday (10/11/2012)<br><div class="little-button">12:30</div><div class="little-button">17:00</div><div class="little-button">20:00</div><div style="text-align: left; font-size: 13px; clear:both">Sunday (11/11/2012)<br><div class="little-button">12:30</div><div class="little-button">20:00</div></div></div>'
                    },
                    {
                        id: 2,
                        title: 'Anna Karenina',
                        description: 'Set in late-19th-century Russia high-society, the aristocrat Anna Karenina enters into a life-changing affair with the affluent Count Vronsky.',
                        imageUrl: 'http://t1.gstatic.com/images?q=tbn:ANd9GcT75AYSk_CjiBVUsSgkvaIuIBLuQxCM19l1vFcEsb3pYtlRw_ZeQlRIIIeshA',
                        logoUrl: 'http://t1.gstatic.com/images?q=tbn:ANd9GcT75AYSk_CjiBVUsSgkvaIuIBLuQxCM19l1vFcEsb3pYtlRw_ZeQlRIIIeshA',
                        trailerUrl: 'http://www.youtube.com/watch?v=rPGLRO3fZnQ',
                        showTimesToday: '<div class=little-button>12:30</div><div class=little-button>17:00</div><div class=little-button>20:00</div>',
                        showTimesWeek: 'Showtimes this week:<br><div style=\'text-align: left; font-size: 13px; clear:both\'>Today: (09/11/2012)<br><div class=little-button>12:30</div><div class=little-button>17:00</div><div class=little-button>20:00</div></div><div style="text-align: left; font-size: 13px; clear:both">Saturday (10/11/2012)<br><div class="little-button">12:30</div><div class="little-button">17:00</div><div class="little-button">20:00</div><div style="text-align: left; font-size: 13px; clear:both">Sunday (11/11/2012)<br><div class="little-button">12:30</div><div class="little-button">20:00</div></div></div>'
                    },
                    {
                        id: 3,
                        title: 'A Good Day to Die Hard',
                        description: 'John McClane travels to Russia to help out his seemingly wayward son, Jack, only to discover that Jack is a CIA operative working to prevent a nuclear-weapons heist, causing the father and son to team up against underworld forces.',
                        imageUrl: 'http://www.iplanit.ie/wp-content/uploads/2012/11/diehard.jpeg',
                        logoUrl: 'http://www.iplanit.ie/wp-content/uploads/2012/11/diehard.jpeg',
                        trailerUrl: 'http://www.youtube.com/watch?v=oZlGkBJj4Ms',
                        showTimesToday: '<div class=little-button>11:30</div><div class=little-button>12:40</div>',
                        showTimesWeek: 'Showtimes this week:<br><div style=\'text-align: left; font-size: 13px; clear:both\'>Today: (09/11/2012)<br><div class=little-button>11:30</div><div class=little-button>12:40</div></div><div style="text-align: left; font-size: 13px; clear:both">Saturday (10/11/2012)<br><div class="little-button">12:30</div><div class="little-button">17:00</div><div class="little-button">20:00</div><div style="text-align: left; font-size: 13px; clear:both">Sunday (11/11/2012)<br><div class="little-button">12:30</div><div class="little-button">20:00</div></div></div>'
                    },
                    {
                        id: 4,
                        title: 'The Expendables 2 ',
                        description: 'Mr. Church reunites the Expendables for what should be an easy paycheck, but when one of their men is murdered on the job, their quest for revenge puts them deep in enemy territory and up against an unexpected threat.',
                        imageUrl: 'http://www.iplanit.ie/wp-content/uploads/2012/11/expendables2.jpeg',
                        logoUrl: 'http://www.iplanit.ie/wp-content/uploads/2012/11/expendables2.jpeg',
                        trailerUrl: 'http://www.youtube.com/watch?v=oZlGkBJj4Ms',
                        showTimesToday: '<div class=little-button>15:20</div><div class=little-button>17:40</div><div class=little-button>18:00</div><div class=little-button>20:20</div>',
                        showTimesWeek: 'Showtimes this week:<br><div style=\'text-align: left; font-size: 13px; clear:both\'>Today: (09/11/2012)<br><div class=little-button>15:20</div><div class=little-button>17:40</div><div class=little-button>18:00</div><div class=little-button>20:20</div></div><div style="text-align: left; font-size: 13px; clear:both">Saturday (10/11/2012)<br><div class="little-button">12:30</div><div class="little-button">17:00</div><div class="little-button">20:00</div><div style="text-align: left; font-size: 13px; clear:both">Sunday (11/11/2012)<br><div class="little-button">12:30</div><div class="little-button">20:00</div><div class="little-button">21:00</div></div></div>'
                    }
                ]
            }
        ],
        model: 'AppBarbados.model.cinema',
        storeId: 'CinemaStore',
        proxy: {
            type: 'ajax',
            reader: {
                type: 'json',
                idProperty: 'id'
            }
        }
    }
});