/*
 * File: app/store/HomeListStore.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AppBarbados.store.HomeListStore', {
    extend: 'Ext.data.Store',
    alias: 'store.HomeListStore',

    requires: [
        'AppBarbados.model.HomeListModel'
    ],

    config: {
        data: [
            {
                atractionId: 1,
                name: 'Restaurants',
                image: 'resources/images/icn-restaurants@2x.png'
            },
            {
                atractionId: 2,
                name: 'Cinemas',
                image: 'resources/images/icn-cinemas@2x.png'
            },
            {
                atractionId: 3,
                name: 'Events',
                image: 'resources/images/icn-events@2x.png'
            },
            {
                atractionId: 4,
                name: 'Crop Over Bands',
                image: 'resources/images/icn-cropoverbands@2x.png'
            },
            {
                atractionId: 5,
                name: 'Concerts',
                image: 'resources/images/icn-concerts@2x.png'
            }
        ],
        model: 'AppBarbados.model.HomeListModel',
        storeId: 'HomeListStore',
        proxy: {
            type: 'ajax',
            reader: {
                type: 'json'
            }
        }
    }
});