/*
 * File: app/view/CinemasView.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AppBarbados.view.CinemasView', {
    extend: 'Ext.form.Panel',
    alias: 'widget.cinemas',

    config: {
        scrollable: false,
        items: [
            {
                xtype: 'dataview',
                itemId: 'liststyleone',
                minHeight: 420,
                itemTpl: [
                    '<div style="padding: 15px 10px; border-bottom: 1px solid #ddd;">',
                    '<img src="{logoUrl}" style="float:left; width: 50px; heigth: 50px; margin-right: 10px" />',
                    '<div style="float: left; ">{name}</div><br />',
                    '<div style="float:left; font-size: 12px;">{address}</div>',
                    '<div style="clear: both"></div>',
                    '</div>'
                ],
                store: 'CinemaStore'
            },
            {
                xtype: 'panel',
                centered: true,
                docked: 'top',
                html: '<img src="resources/images/reggaebanner@2x.jpg" width="257" height="96" /><div style="margin-right: 5px; padding-bottom: 3px">Click outside this box to close Ad</div>',
                left: 25,
                style: 'top: 100px !important; left: 25px !important;  width: 269px; font-size: 12px; text-align: center; -webkit-box-shadow: none; z-index: 10 !important; background-color: black;font-weight: bold;',
                top: 100,
                zIndex: 10,
                hideOnMaskTap: true,
                modal: true,
                scrollable: false
            }
        ]
    }

});