/*
 * File: app/view/CinemasView.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.CinemasView', {
    extend: 'Ext.form.Panel',
    alias: 'widget.cinemas',

    config: {
        items: [
            {
                xtype: 'list',
                docked: 'top',
                height: '420px',
                itemId: 'mylist',
                layout: {
                    type: 'fit'
                },
                itemTpl: [
                    '<img src="{logourl}" style="float:left; width: 50px; heigth: 50px; margin-right: 10px" />',
                    '<div style="float: left; ">{name}</div><br />',
                    '<div style="float:left; font-size: 12px;">{address}</div>',
                    '<div style="clear: both"></div>'
                ],
                store: 'CinemaStore'
            }
        ],
        listeners: [
            {
                fn: 'onMylistSelect',
                event: 'select',
                delegate: '#mylist'
            }
        ]
    },

    onMylistSelect: function(dataview, record, options) {
        //Ext.Msg.alert('Selected!', 'You selected ' + record.get('name'));
        var myView = Ext.getCmp('my-navigation-view');

        myView.push(
        {
            xtype: 'stablishmentview',
            title: record.get('name'),
            scrollable: false,
            items: 
            [
            {
                xtype: 'image',
                height: 100,
                width: 320,
                docked: 'top',
                src: record.get('imageurl'),
                scrollable: false,
                style: 'padding-bottom: 10px'
            },
            {
                style: 'padding: 0 10px',
                scrollable: false,
                xtype: 'label',
                html: '<a href="mailto:' + record.get('email') + '" title="Send Email" style="font-size: 12px; color: #333; text-decoration: none">E-mail: ' + record.get('email') + '</a>'
            },
            {
                style: 'padding: 0 10px',
                scrollable: false,
                xtype: 'label',
                html: '<a href="tel:' + record.get('phone') + '" title="Telephone" style="font-size: 12px; color: #333; text-decoration: none">Telephone: ' + record.get('phone') + '</a>'
            },
            {
                style: 'padding: 0 10px',
                scrollable: false,
                xtype: 'label',
                html: '<a href="tel:' + record.get('address') + '" title="Address" style="font-size: 12px; color: #333; text-decoration: none">Address: ' + record.get('address') + '</a>'
            }
            ]
        }
        );
    }

});