/*
 * File: app/view/HomePanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.HomePanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.homepanel',

    config: {
        items: [
            {
                xtype: 'button',
                border: 0,
                docked: 'top',
                height: '46px',
                id: 'btnBannerAd',
                style: 'background: url(resources/images/top-example-ad.jpg) repeat; -webkit-border-radius: 0'
            },
            {
                xtype: 'button',
                border: 0,
                docked: 'top',
                height: '77px',
                id: 'btnRestaurants',
                style: 'background: url(resources/images/bg-gradient-tableview-cel.jpg) repeat; -webkit-border-radius: 0',
                text: 'Restaurants'
            },
            {
                xtype: 'button',
                border: 0,
                docked: 'top',
                height: '77px',
                id: 'btnCinemas',
                style: 'background: url(resources/images/bg-gradient-tableview-cel.jpg) repeat; -webkit-border-radius: 0',
                text: 'Cinemas'
            },
            {
                xtype: 'button',
                border: 0,
                docked: 'top',
                height: '70px',
                id: 'btnEvents',
                style: 'background: url(resources/images/bg-gradient-tableview-cel.jpg) repeat; -webkit-border-radius: 0',
                text: 'Events'
            },
            {
                xtype: 'button',
                border: 0,
                docked: 'top',
                height: '70px',
                id: 'btnCropOverBands',
                style: 'background: url(resources/images/bg-gradient-tableview-cel.jpg) repeat; -webkit-border-radius: 0',
                text: 'Crop Over Bands'
            },
            {
                xtype: 'button',
                border: 0,
                docked: 'top',
                height: '70px',
                id: 'btnConcerts',
                style: 'background: url(resources/images/bg-gradient-tableview-cel.jpg) repeat; -webkit-border-radius: 0',
                text: 'Concerts'
            }
        ]
    }

});