/*
 * File: app/view/MyNavigationView.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyNavigationView', {
    extend: 'Ext.navigation.View',
    alias: 'widget.MyNavigationView',

    requires: [
        'MyApp.view.HomePanel'
    ],

    config: {
        id: 'my-navigation-view',
        scrollable: true,
        useTitleForBackButtonText: true,
        items: [
            {
                xtype: 'homepanel',
                id: 'barbadosView',
                itemId: 'barbadosView',
                ui: 'light',
                scrollable: 'vertical',
                title: 'Barbados'
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'button',
                        border: 0,
                        centered: true,
                        height: 52,
                        style: 'background:none',
                        width: 93,
                        iconAlign: 'top',
                        iconCls: 'home',
                        iconMask: true,
                        text: 'Home'
                    }
                ]
            }
        ]
    }

});