/*
 * File: app/view/MyTabPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AppBarbados.view.MyTabPanel', {
    extend: 'Ext.tab.Panel',

    requires: [
        'AppBarbados.view.mapview'
    ],

    config: {
        layout: {
            animation: false,
            type: 'card'
        },
        items: [
            {
                xtype: 'navigationview',
                title: 'Home',
                iconCls: 'home',
                id: 'my-navigation-view',
                itemId: 'my-navigation-view',
                useTitleForBackButtonText: true,
                items: [
                    {
                        xtype: 'panel',
                        title: 'Barbados',
                        items: [
                            {
                                xtype: 'button',
                                border: 0,
                                docked: 'top',
                                height: '46px',
                                id: 'btnBannerAd',
                                style: 'background: url(resources/images/top-example-ad@2x.jpg) repeat; -webkit-border-radius: 0; background-size: 320px;'
                            },
                            {
                                xtype: 'dataview',
                                itemId: 'dvHomeList',
                                minHeight: 330,
                                itemTpl: [
                                    '<div style="padding: 15px 10px; border-bottom: 1px solid #ddd;">',
                                    '<img src="{image}" style="float:left; width: 50px; heigth: 50px; margin-right: 10px" />',
                                    '<div style="float: left; margin: 15px;">{name}</div><br />',
                                    '<div style="clear: both"></div>',
                                    '</div>'
                                ],
                                store: 'HomeListStore'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'navigationview',
                title: 'About',
                iconCls: 'info',
                ui: '',
                useTitleForBackButtonText: true,
                items: [
                    {
                        xtype: 'formpanel',
                        title: 'About',
                        items: [
                            {
                                xtype: 'label',
                                html: 'This is your definitve guide and app to keep you up-to-date on everything that is exciting in our beautiful island.',
                                style: 'font-size:14px; margin-bottom: 10px'
                            },
                            {
                                xtype: 'textfield',
                                label: 'Name',
                                labelAlign: 'top'
                            },
                            {
                                xtype: 'textfield',
                                label: 'Phone',
                                labelAlign: 'top'
                            },
                            {
                                xtype: 'textareafield',
                                label: 'Message',
                                labelAlign: 'top'
                            },
                            {
                                xtype: 'button',
                                text: 'Send'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'navigationview',
                title: 'Advertise',
                iconCls: 'favorites',
                items: [
                    {
                        xtype: 'formpanel',
                        title: 'Advertise',
                        items: [
                            {
                                xtype: 'label',
                                html: 'Let us know about your business. Give us the info and we will review it',
                                style: 'font-size:14px; margin-bottom: 10px'
                            },
                            {
                                xtype: 'textfield',
                                label: 'Business Name',
                                labelAlign: 'top'
                            },
                            {
                                xtype: 'textfield',
                                label: 'Phone',
                                labelAlign: 'top'
                            },
                            {
                                xtype: 'textfield',
                                label: 'Email',
                                labelAlign: 'top'
                            },
                            {
                                xtype: 'textfield',
                                label: 'Phone',
                                labelAlign: 'top'
                            },
                            {
                                xtype: 'textareafield',
                                label: 'Description',
                                labelAlign: 'top'
                            },
                            {
                                xtype: 'button',
                                text: 'Send'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'mapview',
                title: 'Maps',
                iconCls: 'maps'
            }
        ],
        tabBar: {
            docked: 'bottom'
        },
        listeners: [
            {
                fn: 'onDvHomeListItemTap',
                single: false,
                event: 'itemtap',
                delegate: '#dvHomeList'
            }
        ]
    },

    onDvHomeListItemTap: function(dataview, index, target, record, e, options) {
        //Ext.Msg.alert('Selected!', 'You selected ' + record.get('name'));
        var myView = Ext.getCmp('my-navigation-view');

        var namewithoutspaces = record.data.name;
        namewithoutspaces = namewithoutspaces.replace(/\s+/g, '').toLowerCase();


        myView.push(
        {
            xtype: namewithoutspaces,
            title: record.data.name
        }
        );
    }

});