/*
 * File: app/controller/MainController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.MainController', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "button#btnRestaurants": {
                tap: 'onBtnRestaurantsTap'
            },
            "button#btnBannerAd": {
                tap: 'onBtnBannerAdTap'
            },
            "button#btnCinemas": {
                tap: 'onBtnCinemasTap'
            }
        }
    },

    onBtnRestaurantsTap: function(button, e, options) {
        var myView = Ext.getCmp('my-navigation-view');

        myView.push(
        {
            xtype: 'mapview',
            title: 'Map',
            scrollable: false
        }
        );
    },

    onBtnBannerAdTap: function(button, e, options) {
        //window.open('http://www.iplanit.ie', '_blank');
    },

    onBtnCinemasTap: function(button, e, options) {
        var myView = Ext.getCmp('my-navigation-view');

        myView.push(
        {
            xtype: 'cinemas',
            title: 'Cinemas'
        }
        );
    }

});