/*
 * File: app/controller/MapControllers.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.MapControllers', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "mapview": {
                centerchange: 'onMapCenterChange'
            }
        }
    },

    onMapCenterChange: function(map, gmap, center, options) {
        var image = 'http://www.iplanit.ie/wp-content/uploads/2012/10/olympus-logo.jpeg';
        var marker = new google.maps.Marker({
            position: new google.maps.LatLng(53.273033,-6.208501),
            title : 'testing',
            map: gmap,
            icon: image
        });
    }

});